### ISSUE TITLE
id3 tags not writing all the time?

### ISSUE THREAD

**Issue by ohnx** [benkaiser/stretto#103]
i feel like the artist and album tag don't write properly when it tries to write album art to the file?

try this yourself, see if you have the same problem.

this might be more of an issue with the id3 module used - is it [node-ffmetadata](https://github.com/parshap/node-ffmetadata)? \([this](https://github.com/benkaiser/stretto/blob/master/package.json#L35) seems to point to it, but i might be wrong...\)

**Comment by benkaiser** [comment]
Yeah I feel the same thing, I have suspected this for a while since when syncing music to my phone it seems to show the wrong coverart for ~80% of my files.

When I get around to having some more time for stretto I'll see if I can work out what's causing the issue.

**Comment by ohnx** [comment]
https://github.com/parshap/node-ffmetadata/issues

seems like a couple of others have had this issue, too.

**Comment by ohnx** [comment]
There are other libraries such as https://github.com/Jack12816/id3-writer

**Comment by benkaiser** [comment]
Yeah, we'll have to look into it.

Yeah I saw id3-writer, the thing I don't like about it is it depends on an external binary, and even if that does have builds for all platforms, it means we have to pack a different binary in with each electron build for each platform. The thing I like about node-ffmetadata is that it depends on ffmpeg and we already bundle ffmpeg to do the youtube video to audio conversion.

**Comment by ohnx** [comment]
Worst case, we can emscripten TagLib ;)

**Comment by benkaiser** [comment]
Now that you mention it. This actually looks really cool: https://github.com/bgrins/videoconverter.js
But it has many issues and I don't want to dump the binary ffmpegs just yet.

**Comment by ohnx** [comment]
Poked around and apparently the issue is due to a certain argument. Not able to test right now, but does this work? https://www.npmjs.com/package/ffmetadata-ohnx-fork

**Comment by ohnx** [comment]
#120 should close this, too.
