### ISSUE TITLE
Error when adding music from Library, Youtube, or Soundcloud

### ISSUE THREAD

**Issue by brandontle** [benkaiser/stretto#107]
Great project!

I'm having some trouble after running `node app.js`, going to `localhost:2000`, and trying to add a song. The terminal either logs an error or the server crashes; each error is different. 

Error from adding a Youtube song or playlist; server still runs after error is logged: 
```
Started converting Youtube movie to mp3
Error: Error: ffmpeg exited with code 1: /Users/usr/Music/youtube/coldplay___paradise__official_video_.mp3: No such file or directory 
```

Error from adding a Soundcloud song; server crashes after error is logged: 
```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: ENOENT: no such file or directory, open '/Users/usr/Music/soundcloud/alaska.mp3'
    at Error (native)
```

Error from Regular and Hard Library Scan; server crashes after error is logged. There are .mp3 files in the /Music folder: 
```
{ Error: ENOENT: no such file or directory, scandir '/Users/usr/Music'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/Users/usr/Music' }
/Users/usr/music_server/stretto/library_functions.js:329
    list.forEach(function(item) {
        ^

TypeError: Cannot read property 'forEach' of undefined
    at /Users/usr/music_server/stretto/library_functions.js:329:9
    at /Users/usr/music_server/stretto/util.js:9:21
    at FSReqWrap.oncomplete (fs.js:117:15)
```

OSX El Capitan (10.11.3, 64bit), Node v6.2.2, npm v3.10.6

**Comment by benkaiser** [comment]
Looks like /Users/usr/Music is undefined according to that last error, and as such the youtube and soundcloud fail as they can't download those songs since the music directory doesn't exist.

(to set the music directory go to the webpage, hit the settings icon, and configure it)

**Comment by brandontle** [comment]
Ah thanks! I missed one level when typing the path into the settings. Should've just copy-pasted the path instead.
