### ISSUE TITLE
Support for Authentication

### ISSUE THREAD

**Issue by amritkrs** [benkaiser/stretto#108]
I think support for authentication will make hosting it even more safer.

**Comment by benkaiser** [comment]
Sure would!
Improvement is already on the trello board: https://trello.com/c/C0D4EQSq/54-add-authentication-of-some-sort

Discussion on implementation / Pull requests are welcome 👍

**Comment by amritkrs** [comment]
Thanks @benkaiser. Hope it comes soon!

**Comment by benkaiser** [comment]
@amritkrs you prompted me to add it. So it's now sitting in master :+1: 
You have to edit the config.js file and add your credentials you want (first removing the comments in front of the block). But then when accessing the server over the web it will first prompt you to authenticate.
