### ISSUE TITLE
CJK seems to be stripped out when storing

### ISSUE THREAD

**Issue by normanzb** [benkaiser/stretto#111]
Any Chinese, Korean, Japanese characters seem to be removed and replaced with underscore instead?

Can we keep them as it is just remove punctuations

**Comment by ohnx** [comment]
is this in the filename on the filesystem?

**Comment by benkaiser** [comment]
Yeah is it from the filesystem? Because I'm guessing if it's pulling the name from the filesystem it wants to remove all potentially nasty characters.
If it's from the id3 tags however I can try look into it further.

**Comment by normanzb** [comment]
tested with latest version, doesn't seem have the issue anymore
