### ISSUE TITLE
file extension filter

### ISSUE THREAD

**Issue by juliuste** [benkaiser/stretto#113]
It would be really nice to have some kind of file extension/type filtering available in the config in some form (either selecting as a white- or as a blacklist).
If you - like me - have MP3 and FLAC of multiple files for compatibility reasons (iPhone </3 FLAC), it's really annoying to have each song listed twice in the interface. And you can't even play those FLACs in your browser 😄

**Comment by benkaiser** [comment]
Pull requests welcome :)

General idea of what would need to happen:
- Add option to config
- Edit `library_functions.js` somewhere around https://github.com/benkaiser/stretto/blob/master/library_functions.js#L326
- Add in logic there to strip out filenames based on the list provided in the config

**Comment by benkaiser** [comment]
Closing out, applies to old architecture of Stretto
