### ISSUE TITLE
Remote control endpoints broken

### ISSUE THREAD

**Issue by benkaiser** [benkaiser/stretto#114]
Hitting the remote control endpoints return an `Internal Server Error`:

```
$ curl http://localhost:3000/command/remote_name/next
Internal Server Error
```

**Comment by ohnx** [comment]
Did it work before the switch to express.oi? https://github.com/benkaiser/stretto/commit/5065b0d8cce40a6417dc53cbcb37d74f3b5f0eb7#diff-bb503f3d9047bcd4a5730559f1e16560R391

**Comment by benkaiser** [comment]
Yeah that could be it, I'll take a look at it after work.

**Comment by benkaiser** [comment]
Closed in https://github.com/benkaiser/stretto/commit/98b6319e8ab7e94c139ff5af8ad428a746bbbf54
