### ISSUE TITLE
Missing cover photos suck

### ISSUE THREAD

**Issue by benkaiser** [benkaiser/stretto#115]
So someone told me they aren't a fan of the sloth, my suggestions are either:

Roll with the typical "picture of headphones / music symbol" on simple background.

or...

Use a random unsplash image for each file missing artwork! That way it still looks nice!

This can be done using: `https://unsplash.it/g/512?random`

**Comment by ohnx** [comment]
Could also use the logo:

![09ad3730-7c38-11e5-8fce-2908db77086f](https://cloud.githubusercontent.com/assets/6683648/19530957/ed50912c-9603-11e6-8866-708be3e8271a.png)

**Comment by benkaiser** [comment]
Yeah the logo isn't a bad idea either. I'll run it past the sloth hater and see what she thinks :)

**Comment by benkaiser** [comment]
Closing out, applies to old architecture of Stretto
