### ISSUE TITLE
Duplicates in database pointing to same file

### ISSUE THREAD

**Issue by benkaiser** [benkaiser/stretto#117]
Steps to reproduce:
- Download youtube video.
- Remove file and redownload without scanning

Both instances are still in the database.

**Comment by vikassahu29** [comment]
Possible fix

- update instead of insert while inserting songs downloaded from youtube
- on client side -  replace song in song_collection and at other places don't update anything just render with the new model data

If the fix seems fine. I'll submit a PR.

**Comment by benkaiser** [comment]
That sounds reasonable. There might already be a song update message you can send down instead of implementing that clientside code :)

**Comment by vikassahu29** [comment]
Yes, song update message is there but we'll need to show the notification that youtube song download is complete. So what I'll do is create a new message with [ "yt_update" - "updated" ] - show the notification and call the song update logic from here.

**Comment by benkaiser** [comment]
Sounds good :) put it in a PR and I'll take a look

**Comment by vikassahu29** [comment]
#125 PR Created

**Comment by benkaiser** [comment]
Closing out, applies to old architecture of Stretto
