### ISSUE TITLE
Allow searching of YouTube/SoundCloud directly inside the app

### ISSUE THREAD

**Issue by ohnx** [benkaiser/stretto#118]
A possibility would be that at the bottom of the search results, there is a link to click that says "Search YouTube..."

It would allow someone to not have to open YouTube in order to navigate to a specific song.

**Comment by benkaiser** [comment]
Yeah good idea, I'm almost tempted to make the search of youtube happen automatically if there are <10 or so results too.

**Comment by ohnx** [comment]
https://github.com/MaxGfeller/youtube-search

**Comment by ohnx** [comment]
this is pretty much done
