### ISSUE TITLE
Blank cover photo doesn't update until page reload after one is chosen

### ISSUE THREAD

**Issue by ohnx** [benkaiser/stretto#121]
Blank cover photo doesn't update until page reload after one is chosen. Steps to reproduce:
1. Get a new song in your library
2. Give it a cover photo
3. Watch as when you hit 'save', the old photo stays there
4. Reload the page and see the new photo

probably a result of the changes in 73c122b9313d306ab5ab7b45ee0074a7c3439c88, but this issue might have existed before as well.

**Comment by benkaiser** [comment]
Closing out, applies to old architecture of Stretto
