### ISSUE TITLE
Electron build doesn't allow copy paste of youtube urls

### ISSUE THREAD

**Issue by joellewillder** [benkaiser/stretto#128]
Hi, sloth hater here,

I am trying to download a youtube video in electron and it doesn't do anything. Right click also does nothing.

Please fix so the I can use Stretto!

(p.s. can't believe your girlfriend has to write on here to get an issue through)

**Comment by ohnx** [comment]
😂

Are you sure you have an internet connection when you're trying to download?

Youtube downloading with the latest version of stretto seems to work for me.

**Comment by benkaiser** [comment]
Yeah the internet connection was fine (we were watching the YouTube video
in Chrome before trying in Stretto.

She's on an Mac, so it could be something to do wtih the electron builds on
Mac. I needed to do a new build soon just to get any fixes from Electron as
well as including some of the new features that have come together this
year.

**Comment by benkaiser** [comment]
Closing out, applies to old architecture of Stretto
