### ISSUE TITLE
Only menu text

### ISSUE THREAD

**Issue by ruttydm** [benkaiser/stretto#129]
GET http://localhost:2000/static/lib/head.min.js (index):9 
(index):12 Uncaught ReferenceError: head is not defined(…)(anonymous function) @ (index):12
(index):364 Uncaught ReferenceError: head is not defined(…)(anonymous function) @ (index):364

I only see some text from the menu, i installed everything properly.

**Comment by ohnx** [comment]
Hi!

Seems like headjs didn't install properly.

Did you try running `npm install` again? maybe that will fix it.

**Comment by benkaiser** [comment]
Yeah, normally when this happens it's a bower issue. Try `npm install`
again and paste the logs from that here and if that all runs successfully
do a `bower install`

**Comment by PraveenkumarDonga** [comment]
Hi!
I am facing the same issues.
I did again npm install as you said, but i am getting this 
npm WARN lifecycle stretto@0.0.6~postinstall: cannot run in wd %s %s (wd=%s) stretto@0.0.6 ./node_modules/grunt-cli/bin/grunt /home/smartron/stretto
could please anyone help me this.


Environment Details:
Os:Ubuntu16.04 LTS
node-v: 7.4.0
npm-v: 4.2.0
nodejs -v:4.2.6

Thanks:
praveen.

**Comment by benkaiser** [comment]
@PraveenkumarDonga I googled your issue `cannot run in wd %s %s (wd=%s)` and found this: http://stackoverflow.com/a/19132229/485048
Give that a try and see if you can get anywhere

**Comment by xanthos84** [comment]
got the same error (run install with root)  so
npm install --unsafe-perm 

worked to fix!
