### ISSUE TITLE
Stretto 2.0

### ISSUE THREAD

**Issue by benkaiser** [benkaiser/stretto#130]
I wanted to create an issue to briefly draft my plans for the next iteration of Stretto, creating a different but still awesome music player based on the learning over the last several years from this project.

Firstly, I want to try creating it with no storage of song files. This is very counter-intuitive to the way Stretto has performed so far. Instead, all songs can simply be played from the [youtube](https://developers.google.com/youtube/js_api_reference) or [soundcloud](https://developers.soundcloud.com/docs/api/html5-widget) embedded players directly (like how we currently perform youtube search / instant mixes).

Down the track I might add a backend that supports linking into so you can store your own song files, or even cross-integrate it with a file-storage service so you can use that as the backing, but that's an extension feature.

The upside to this method however, is massively reduced barrier to entry. I want to be able to host Stretto as a public website and allow people to use the player without having to sign in. This can be done through local storage storing the track / playlist data. The extension of this is to allow users to perform social sign in (my preference) or manual account creation to sync their 'library' between machines.

There are several other tasks that need to happen for this player to be successful:

- [x] General track importing, so you can give it a list of tracks and it can find them on youtube/soundcloud. This would work best with integrations, first of all for Stretto's current library files, then I would also like to do Spotify as they have a [user playlist api](https://developer.spotify.com/web-api/get-list-users-playlists/).
- [ ] The appearance of not a completely empty library on first load. I think this could be done with a 'splash screen' of top music charts from the like of [itunes RSS feeds](https://rss.itunes.apple.com/us/?urlDesc=%2Fgenerator) and such.

Other nice to haves that won't be in the initial version / MVP:

- [x] Offline support, that will take some more thinking, and normally the usecase for offline is mobile so may be considered separately
- [x] Mobile application, a mobile counterpart allowing the social sign in and then streaming and or downloading of tracks. How the 'downloading' part would work here, is that the server would have an endpoint like `/youtube/<youtube_id>` and in the background it would stream the file from youtube, convert it to mp3 and stream that out over HTTP. Similar story with soundcloud except we can provide direct mp3 urls for soundcloud.

I figure since this is vastly different to how Stretto is currently, I will rewrite this from the ground up, so I do expect development of this to take a significant period of time (largely dependent on how free I am / how hectic my new job is in January). But I believe this change will reinvent Stretto and bring it to a much larger audience.

**Comment by ohnx** [comment]
Sounds cool!

Maybe in the future, there could also be functionality to save songs locally 
(like with Spotify) and play those (which is pretty much what you have right now 😛).

**Comment by benkaiser** [comment]
Yeah, too right! The best way to do that I think would be through an electron app, so that becomes the "desktop app" version that allows local saving of music. And we keep 2.0 as the web based version that it all centrally revolves around.

**Comment by ohnx** [comment]
That's what I was thinking of, too - make the new web-based version first,
then create an app (electron) that allows for local storage.

On November 28, 2016 12:24 PM, "Benjamin Kaiser" <notifications@github.com>
wrote:

Yeah, too right! The best way to do that I think would be through an
electron app, so that becomes the "desktop app" version that allows local
saving of music. And we keep 2.0 as the web based version that it all
centrally revolves around.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/benkaiser/stretto/issues/130#issuecomment-269509750>,
or mute the thread

**Comment by benkaiser** [comment]
BTW the work I am starting is going on in the `next` branch: https://github.com/benkaiser/stretto/tree/next

All I have so far is the boilerplate and a basic theme switcher (yayy!!!)

**Comment by benkaiser** [comment]
Today my task was to deploy it, and here you can see the initial version running:
https://next.kaiserapps.com

So so many features to go still. But you can add tracks from youtube and listen to them, but that's about it!

**Comment by ohnx** [comment]
I like the new cleanliness and the themes :wink:

You're probably going to fix this, but the settings menu should restore the current theme when you click on it :)

**Comment by benkaiser** [comment]
Oh you mean restoring the select box, yeah that's a good point. I'm so much
more focused on adding features right now than bugfixes. Next feature I
want is adding SoundCloud, then a nice importer so I can pull my old
stretto library in :)

**Comment by benkaiser** [comment]
Closing this issue as I've replaced the master branch with the next branch (moving the master branch to `oldDesktopVersion`)
