### ISSUE TITLE
If file has no "title" tag, use the filename

### ISSUE THREAD

**Issue by ryanmjacobs** [benkaiser/stretto#131]
Hi and thank you for this wonderful project!

I have a folder with some .m4a files, but in Stretto they show up blank. I'm guessing this is because the .m4a files lack any sort of ID3 tag data. Would it be possible to use the filename instead when this scenario is encountered?

![stretto-blank-name](https://cloud.githubusercontent.com/assets/4251257/22859285/55aa245e-f08b-11e6-93a2-ccec8f09240c.png)

I'm not yet familiar with the codebase, or else I would try implementing it myself. Any pointers would be appreciated.

**Comment by benkaiser** [comment]
Interesting, we should have handling for that:

https://github.com/benkaiser/stretto/blob/master/library_functions.js#L124

Perhaps you could put in some console output lines around there and then hard rescan that song (right click it -> hard rescan) and then see which points it's hitting.

**Comment by ryanmjacobs** [comment]
Okay, thanks for the tip. Everything looked all right, so I just noted which songs had this problem.

It turns out that these files are in fact `mp3` files, however they possess no tag data at all. (I had converted them by decoding the `.m4a` files directly and piping the output into LAME... therefore no tag data was written.)

So, perhaps if ID3 title is blank, stretto can use the file name instead?

**Comment by benkaiser** [comment]
I feel like that's rather hacky... not listening to what the id3 tags say the data is (blank in this case).
If you're familiar with piping things around and such I'd recommend writing a script again to merge the filename onto all the title id3 attributes. Alternatively I'm pretty sure a program called [kid3](https://kid3.sourceforge.io/) can do that in bulk quite easily (does regex formatting and stuff too if you want to get fancy).

Going to close this for now as I don't think we should handle special cases when the id3 tags are set to blank.
