### ISSUE TITLE
Add a password or session management

### ISSUE THREAD

**Issue by h3ct0rjs** [benkaiser/stretto#135]
Hi @benkaiser Wow this repo is a wonderful job, 
after doing a quick search for web players and following the DRY concept I just found this repo, so thank you for share this piece of code. I was wondering that if you would add a session management or a password policy to access to the web service What would you implement, I would like to use this project for my personal music :smile: using a small box with 512Mb, this repo has all the features that I was looking for, have you think about the session management feature?

Thanks in advance, 
Hector F.

**Comment by ohnx** [comment]
Hi @h3ct0rjs 

I am not Ben, but I wanted to let you know that there is in fact already a way to implement basic HTTP authentication by editing `config.js`, see [this link](https://github.com/benkaiser/stretto/blob/master/config.js#L28).

Mason

**Comment by benkaiser** [comment]
Yes we did indeed add that basic HTTP auth, you've got a better memory than me @ohnx !

Just a note @h3ct0rjs I'm working on a newer version of Stretto in the `next` branch which works a fair bit differently to the current Stretto. But just letting you know maintenance / new features will be much lower priority in the current version of stretto :)

**Comment by h3ct0rjs** [comment]
Hi @ohnx @benkaiser, 
I'm checking the current code to see how can I help and trying to understand everything in the current project, the basic http authentication is ok to me, my current vm is well hardened with firewall rules that just allow me access from a certain location, I was wondering  if it's posible to use passportjs *remember I'm still checking the code* :smile: 

Regards, 
Hector

**Comment by ohnx** [comment]
@h3ct0rjs from my understanding, passportjs is just a middleware to use, so using it definitely should be possible... Try it out and see!
