### ISSUE TITLE
Collaborate with mStream 

### ISSUE THREAD

**Issue by IrosTheBeggar** [benkaiser/stretto#138]
Hey there,

Saw your project.  i think I'm working on a very similar project called mStream.  It's a music streaming server written in node and it has a lot of similar features.

https://github.com/IrosTheBeggar/mStream

Let me know if you'd be interested in working together on this

**Comment by benkaiser** [comment]
Hey,

Sweet project! I like a lot of aspects of what you've done, really nailing the user adoption with the server setup vid / platform support!

I'm actually taking Stretto in a rather different direction with the next version (see [next](https://github.com/benkaiser/stretto/tree/next) branch), with the aim being to use youtube videos / soundcloud songs as the backing tracks for the entire library, and only needing one server to store the users data / keep it in sync across devices but never having to store the music files themselves.
I'm planning cool features for that like import from Spotify and in-built soundcloud feed browsing but they are still in the works.
You can try out what I have working so far on this page:
https://next.kaiserapps.com/

So as you can see from this direction the underlying fundamentals are quite different, with my main goal being to make it way easier for users to switch to Stretto and not having to handle massive amounts of user media content. You're more than welcome to help out with Stretto, but I'm not looking to stick with user-managed libraries / servers in the future 😄
