### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by ghost** [benkaiser/stretto#141]
i see an option to import here

https://next.kaiserapps.com/import

however i see no option to export in a similar fashion

**Comment by benkaiser** [comment]
Correct, since this is the 'next' version of stretto. That import page is for the original version.

I need to add export to the new one, but you can essentially achieve the behavior right now by dumping out the localStorage

**Comment by cup** [comment]
@benkaiser this is a neat project - but i am absolutely not going to use it until thats an option

it seems the whole selling point of a project like this is it being open: thats all tossed out the window if you cant export your own data - just becomes another facebook twitter etc

**Comment by benkaiser** [comment]
Once again, to add to the history. Stretto 1.x dumps it's DB in a file on the machine it runs on, so I guess for 1.x users having the data wasn't a concern.

Like I said for this version though, the one hosted at next.kaiserapps.com, the library data itself never leaves your machine until you choose to sync it. It stays in browser localStorage, of which you are free to dump out (it's just JSON).

You're welcome to add an export feature, I'll accept a PR. But right now that's not a use case I'm focusing on.

**Comment by benkaiser** [comment]
Closing as the original commented is no longer here... for anyone curious in the future, you can actually export your data at:

https://next.kaiserapps.com/backup/
