### ISSUE TITLE
Local Files

### ISSUE THREAD

**Issue by infosisio** [benkaiser/stretto#143]
So why we can no longer import local files? If so, why? No source has a good enough bitrate for audiophiles...

**Comment by infosisio** [comment]
@benkaiser I don't know what service that may be. Have you considered starting that using the old code and calling it something like "StrettoLocal"? I mean, without being able to use my own library from the web, I personally wouldn't have a need to use Stretto.

**Comment by benkaiser** [comment]
Well, the branch still exists for the old code. Anyone is welcome to continue using that / maintaining that. You're not obligated to upgrade to the new version.

As for what service that may be, it would have to be implemented. Essentially a wrapper around amazon s3 or something to basically store the files online, and then a way in Stretto to import the metadata for all those files / keep them in sync. This is definitely beyond the scope of what I'm wanting to implement, but if someone wants to take charge I'll help out on the integration side

**Comment by infosisio** [comment]
@benkaiser It's your own project and I have no right to judge your decisions in any way, but you really did have something special there with Stretto being a solution to enable anyone to have their own cloud music player. Just my two cents.

**Comment by edenvicary** [comment]
@infosisio I think the s3 wrapper is a solid suggestion, plus it's better that Stretto doesn't get stuck in the past.

**Comment by benkaiser** [comment]
Closing this issue out as out of scope. Anyone wishing to implement a local connector / a way to upload local music to a service to have them streamed is welcome to submit a PR.
