### ISSUE TITLE
Spotify login doesn't appear to work

### ISSUE THREAD

**Issue by dantheman213** [benkaiser/stretto#144]
I tried to login which requires using Facebook login on Spotify's page. After attempting to do got this error.
<img width="1145" alt="Screen Shot 2019-05-02 at 6 12 20 PM" src="https://user-images.githubusercontent.com/10934533/57115826-13260180-6d06-11e9-8332-b8345a5ffa04.png">

**Comment by benkaiser** [comment]
You'll need to create a `.env` file and add to it your:

```
SPOTIFY_CLIENT_ID=<SPOTIFY_CLIENT_ID>
```

**Comment by benkaiser** [comment]
I should document this better, perhaps with a `.env.example` file for you to copy and edit.

**Comment by xtrm0** [comment]
I created a spotify app and put the client id <stretto-git>/.env, and then I ran bin/go. It is loaded on the js. It still doen't appear to work:
![image](https://user-images.githubusercontent.com/1348329/101235269-1beb7000-36bf-11eb-8c9f-6dd4a920d28e.png)

**Comment by benkaiser** [comment]
@xtrm0 you have to configure the spotify app redirect URI to be the URI of where your server is hosted.

Click on "Edit Settings" on the app page of the spotify developer console, then add your redirect URIs. Here is mine for example:

![image](https://user-images.githubusercontent.com/608054/101277633-ea32f000-3809-11eb-91ad-67ed9b555689.png)

**Comment by xtrm0** [comment]
Now it connects to spotify but doesn't get any playlist from it - just opens a new tab with stretto again :stuck_out_tongue_closed_eyes: 
(Same things happens on next.kaiserapps.com)

**Comment by benkaiser** [comment]
Yeah looks like it's busted right now. I'll try work on a fix when I get a chance

**Comment by benkaiser** [comment]
Fixed in 6602709a81e523e2be05ca07274877d81b736d26
