### ISSUE TITLE
Feature request: Allow importing from YouTube playlists

### ISSUE THREAD

**Issue by SuperSandro2000** [benkaiser/stretto#152]
I have my song collection in a public youtube playlist to always be able to access it at friends places. 
Could support be added to import youtube playlists into stretto?

**Comment by benkaiser** [comment]
That support could definitely be added, and in fact is already somewhat
there (you can view mix playlists by right clicking on a song to see the
YouTube mix for a song, which is just a playlist underneath).

Would you be interested in contributing the UI work to add that function
through the add section?

**Comment by SuperSandro2000** [comment]
I would just add it to the current view (https://next.kaiserapps.com/add) and decide based on the URL if it is a video or a playlist.

And about UI work... not my strong side and I am not fluent in js. so I probably take a pass on this.

**Comment by benkaiser** [comment]
@SuperSandro2000 I know you probably lost interest since, but I've added the functionality. The URL you provide on the "Add" screen has to be on a video page with the playlist on the right hand side (i.e. both the v= in the URL and the list=). But if you provide both of those it adds a button to take you to the youtube playlist view, from there you can add the entire playlist to your library in one click.

**Comment by SuperSandro2000** [comment]
You won't find the feature if you do not know it. Sadly it requires a google login.

**Comment by benkaiser** [comment]
@SuperSandro2000 I just tested in incognito, works without a google login.
I decoupled all the youtube calls the other day to be completely scraping based (i.e. no API and no login needed?.
Only need for google now is for syncing, but I have plans to add other authentication methods to.

If you have the Stretto helper extension installed to enable the youtube calls, then this youtube playlist will work:

https://next.kaiserapps.com/mix/hBFl9h-G8Cg+PLsXN4aS9Z11cfEKkWS1CkORwwyHOs5O-k

**Comment by SuperSandro2000** [comment]
> If you have the Stretto helper extension installed to enable the youtube calls, then this youtube playlist will work:

Well, I do not have this.

**Comment by benkaiser** [comment]
Stretto prompts you to install the extension with steps if you load it without the extension active.
Without the extension all the cross origin requests needed to make calls to youtube will not work.

**Comment by SuperSandro2000** [comment]
> Stretto prompts you to install the extension with steps if you load it without the extension active.

I just clicked that annoying pop up away.

I do not plan to install the extension and find something else for my usecase.
