### ISSUE TITLE
Repeat button not working as expected

### ISSUE THREAD

**Issue by anleac** [benkaiser/stretto#161]
👋  from a githubber

On Chrome (Version 87.0.4280.88 (Official Build), MacOS), using your latest extension.

Repeat button appears to put the music tracker back at the start of the song, but pauses (while I'd expect it to repeat). 
See gif for more details:

![repeat](https://user-images.githubusercontent.com/13091188/101766907-c3afd600-3ae3-11eb-91dc-21d5d655a3ae.gif)

**Comment by benkaiser** [comment]
@anleac fixed, pushing to server now
