### ISSUE TITLE
no sound ???

### ISSUE THREAD

**Issue by Orangeskai** [benkaiser/stretto#173]
hello
Can i self hosted this ????
and while running in docker or not me always facing an error like 
always showing install the extension but already installed
and the search is normal but after i choose the music it load and stop no sound no pause button waiting for minute still same
im already try with node js 12 and 10 but still same and some module cannot be installed
thanks.
os debian 10

**Comment by benkaiser** [comment]
Hey @Orangeskai,

You can indeed self-host. You may need some tweaks, because the [domain name is scoped to only localhost or next.kaiserapps.com](https://github.com/benkaiser/Stretto-Helper-Extension/blob/f460f962b8f37f3813a19c88af6fd2250ad8da8b/extension/manifest.json#L20-L35) (the one I host for everyone's use).

What domain are you using?

Also are you following the docker-compose from the README?

**Comment by Orangeskai** [comment]
yes i followed the readme 
 
ohh so i need to build my own extension and put my domain ????
and is there a way to compile it ? rather than using npm run dev ?

**Comment by benkaiser** [comment]
Deprecations warnings should be fine, that should compile the extension for you after you change it to your domain

Were you able to load the extension folder into chrome?

**Comment by Orangeskai** [comment]
i tried to clone the repo and install it

while i npm install shows me this error
~/Stretto-Helper-Extension$ npm install
npm WARN youtube-to-mp3@1.0.0 No repository field.

added 187 packages from 202 contributors and audited 187 packages in 26.556s

19 packages are looking for funding
  run `npm fund` for details

found 4 vulnerabilities (1 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details

and while npm start i have this error

> youtube-to-mp3@1.0.0 start /home/noname/Stretto-Helper-Extension
> webpack

[webpack-cli] Compilation finished
assets by status 132 KiB [cached] 2 assets
runtime modules 1.21 KiB 5 modules
orphan modules 2.81 KiB [orphan] 2 modules
modules by path ./node_modules/ 118 KiB
  modules by path ./node_modules/react-native-ytdl/lib/ 109 KiB
    modules by path ./node_modules/react-native-ytdl/lib/*.js 60.8 KiB 8 modules
    modules by path ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/ 48.1 KiB 8 modules
  modules by path ./node_modules/querystring/*.js 4.51 KiB 3 modules
  ./node_modules/react-native-ytdl/index.js + 1 modules 2.16 KiB [built] [code generated]
  ./node_modules/react-native-ytdl/package.json 1.98 KiB [built] [code generated]
modules by path ./src/*.ts 6.45 KiB
  ./src/background.ts 6.07 KiB [built] [code generated]
  ./src/content.ts 305 bytes [built] [code generated]
  ./src/processMock.ts 82 bytes [built] [code generated]

ERROR in ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/index.js 3:0-84
Module not found: Error: Can't resolve 'react-native/Libraries/Utilities/PolyfillFunctions' in '/home/noname/Stretto-Helper-Extension/node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url'
 @ ./node_modules/react-native-ytdl/lib/sig.js
 @ ./node_modules/react-native-ytdl/lib/index.js 5:12-28
 @ ./node_modules/react-native-ytdl/index.js 1:0-25 3:15-19
 @ ./src/background.ts

ERROR in ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/js/URL.js 1:0-45
Module not found: Error: Can't resolve 'react-native' in '/home/noname/Stretto-Helper-Extension/node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/js'
 @ ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/index.js 11:30-53 5:0-25 5:0-25
 @ ./node_modules/react-native-ytdl/lib/sig.js
 @ ./node_modules/react-native-ytdl/lib/index.js 5:12-28
 @ ./node_modules/react-native-ytdl/index.js 1:0-25 3:15-19
 @ ./src/background.ts

ERROR in ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/js/URL.js 2:0-62
Module not found: Error: Can't resolve 'whatwg-url-without-unicode' in '/home/noname/Stretto-Helper-Extension/node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/js'
 @ ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/index.js 11:30-53 5:0-25 5:0-25
 @ ./node_modules/react-native-ytdl/lib/sig.js
 @ ./node_modules/react-native-ytdl/lib/index.js 5:12-28
 @ ./node_modules/react-native-ytdl/index.js 1:0-25 3:15-19
 @ ./src/background.ts

ERROR in ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/js/URLSearchParams.js 1:0-61
Module not found: Error: Can't resolve 'whatwg-url-without-unicode' in '/home/noname/Stretto-Helper-Extension/node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/js'
 @ ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/index.js 14:10-57 6:0-37 6:0-37
 @ ./node_modules/react-native-ytdl/lib/sig.js
 @ ./node_modules/react-native-ytdl/lib/index.js 5:12-28
 @ ./node_modules/react-native-ytdl/index.js 1:0-25 3:15-19
 @ ./src/background.ts

ERROR in ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/js/ios10Fix.js 7:0-40
Module not found: Error: Can't resolve 'react-native' in '/home/noname/Stretto-Helper-Extension/node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/js'
 @ ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/index.js 1:0-23
 @ ./node_modules/react-native-ytdl/lib/sig.js
 @ ./node_modules/react-native-ytdl/lib/index.js 5:12-28
 @ ./node_modules/react-native-ytdl/index.js 1:0-25 3:15-19
 @ ./src/background.ts

webpack 5.8.0 compiled with 5 errors in 6606 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-to-mp3@1.0.0 start: `webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtube-to-mp3@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/noname/.npm/_logs/2021-06-02T12_52_56_408Z-debug.log

**Comment by benkaiser** [comment]
What node version are you using? You can probably use the latest (14 or 15) to build the extension

**Comment by Orangeskai** [comment]
i use 
node -v
v12.22.1
npm -v
6.14.12

**Comment by benkaiser** [comment]
As for changing the port and domain of your server, that's outside the scope of the help I can provide here. Docker supports running on different ports (port 80 is the default http port, and 443 is the default https port), you might need different privileges to do so.

Good to hear you got it running on localhost!
As for the other machine, you're likely accessing it with the machine IP address right? You'll need to add that IP address as part of the list in the extension I sent you.

For trying to get that to build, have you tried the latest nodejs version (15.x.x)?

**Comment by benkaiser** [comment]
`npm start` runs for me on node 14.6, the package-lock.json file should be ensuring the right versions of all the packages between us, so they should behave the same on both machines.

What OS are you building on?

**Comment by Orangeskai** [comment]
still error sadly

root@debian:/home/user/Stretto-Helper-Extension# node -v
v14.17.0
root@debian:/home/user/Stretto-Helper-Extension# npm install
npm WARN youtube-to-mp3@1.0.0 No repository field.

audited 192 packages in 2.465s

20 packages are looking for funding
  run `npm fund` for details

found 4 vulnerabilities (1 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
root@debian:/home/user/Stretto-Helper-Extension# npm start

> youtube-to-mp3@1.0.0 start /home/user/Stretto-Helper-Extension
> webpack

[webpack-cli] Compilation finished
assets by status 281 KiB [cached] 2 assets
runtime modules 1.21 KiB 5 modules
orphan modules 2.81 KiB [orphan] 2 modules
modules by path ./node_modules/ 265 KiB
  modules by path ./node_modules/react-native-ytdl/ 118 KiB 21 modules
  modules by path ./node_modules/whatwg-url-without-unicode/ 132 KiB
    modules by path ./node_modules/whatwg-url-without-unicode/lib/*.js 69.4 KiB 8 modules
    modules by path ./node_modules/whatwg-url-without-unicode/*.js 1.13 KiB 2 modules
    modules by path ./node_modules/whatwg-url-without-unicode/node_modules/ 61.3 KiB 2 modules
  ./node_modules/webidl-conversions/lib/index.js 9.67 KiB [built] [code generated]
  ./node_modules/base64-js/index.js 3.84 KiB [built] [code generated]
  ./node_modules/ieee754/index.js 2.1 KiB [built] [code generated]
modules by path ./src/*.ts 6.45 KiB
  ./src/background.ts 6.07 KiB [built] [code generated]
  ./src/content.ts 305 bytes [built] [code generated]
  ./src/processMock.ts 82 bytes [built] [code generated]

ERROR in ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/index.js 3:0-84
Module not found: Error: Can't resolve 'react-native/Libraries/Utilities/PolyfillFunctions' in '/home/user/Stretto-Helper-Extension/node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url'
 @ ./node_modules/react-native-ytdl/lib/sig.js
 @ ./node_modules/react-native-ytdl/lib/index.js 5:12-28
 @ ./node_modules/react-native-ytdl/index.js 1:0-25 3:15-19
 @ ./src/background.ts

ERROR in ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/js/URL.js 1:0-45
Module not found: Error: Can't resolve 'react-native' in '/home/user/Stretto-Helper-Extension/node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/js'
 @ ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/index.js 11:30-53 5:0-25 5:0-25
 @ ./node_modules/react-native-ytdl/lib/sig.js
 @ ./node_modules/react-native-ytdl/lib/index.js 5:12-28
 @ ./node_modules/react-native-ytdl/index.js 1:0-25 3:15-19
 @ ./src/background.ts

ERROR in ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/js/ios10Fix.js 7:0-40
Module not found: Error: Can't resolve 'react-native' in '/home/user/Stretto-Helper-Extension/node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/js'
 @ ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/index.js 1:0-23
 @ ./node_modules/react-native-ytdl/lib/sig.js
 @ ./node_modules/react-native-ytdl/lib/index.js 5:12-28
 @ ./node_modules/react-native-ytdl/index.js 1:0-25 3:15-19
 @ ./src/background.ts

webpack 5.8.0 compiled with 3 errors in 3781 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-to-mp3@1.0.0 start: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youtube-to-mp3@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-03T02_57_33_209Z-debug.log
root@debian:/home/user/Stretto-Helper-Extension#

**Comment by Orangeskai** [comment]
i try with docker image node js buster i got different error like this


ERROR in ./node_modules/react-native/Libraries/Utilities/PolyfillFunctions.js 28:31
Module parse failed: Unexpected token (28:31)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  * @see https://github.com/facebook/react-native/issues/934
|  */
> function polyfillObjectProperty<T>(
|   object: {...},
|   name: string,
 @ ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/index.js 3:0-84 11:2-16 12:2-16
 @ ./node_modules/react-native-ytdl/lib/info.js
 @ ./node_modules/react-native-ytdl/lib/index.js 1:16-33
 @ ./node_modules/react-native-ytdl/index.js 1:0-25 3:15-19
 @ ./src/background.ts

ERROR in ./node_modules/react-native/index.js 14:7
Module parse failed: Unexpected token (14:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| // Components
> import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
| import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
| import typeof Button from './Libraries/Components/Button';
 @ ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/js/ios10Fix.js 7:0-40 9:33-49 11:4-15
 @ ./node_modules/react-native-ytdl/lib/__REACT_NATIVE_YTDL_CUSTOM_MODULES__/url/index.js 1:0-23
 @ ./node_modules/react-native-ytdl/lib/info.js
 @ ./node_modules/react-native-ytdl/lib/index.js 1:16-33
 @ ./node_modules/react-native-ytdl/index.js 1:0-25 3:15-19
 @ ./src/background.ts

**Comment by Orangeskai** [comment]
ok i get it worked but i need to change manually from background.js and manifest.json

but the build tool still error i try to experiment by adding 
>externals: { "react-native": true },
>
![image](https://user-images.githubusercontent.com/42552126/120705959-aa13a800-c4e2-11eb-8dbf-1945ecb38db7.png)

in the webpack.config.js

the script can run successfully with no error but after installing to the chrome i get another problem like
![image](https://user-images.githubusercontent.com/42552126/120704912-5e143380-c4e1-11eb-91f1-4af86d1f8d75.png)

**Comment by benkaiser** [comment]
Good idea, skip the build script and just modify background.js manually

**Comment by benkaiser** [comment]
so reset to master first, that way you'll undo your broken changes, and just manually modify next.kaiserapps.com in the built background.js to your custom domain/ip address and port

**Comment by Orangeskai** [comment]
okay thanks :) and i will try to search the problem for build process
