### ISSUE TITLE
Song can appear multiple times in a playlist

### ISSUE THREAD

**Issue by benkaiser** [benkaiser/stretto#51]
Wut? They are the same. Clicking any of them always highlights one of them.

![screenshot2](https://cloud.githubusercontent.com/assets/608054/8507881/08122f54-229a-11e5-83d5-14c3145669a8.jpg)

**Comment by benkaiser** [comment]
Could not reproduce. Either already fixed and I just don't remember, or I couldn't recreate the bug.

**Comment by ohnx** [comment]
There are two ways to replicate this:
Either actually add them both, or scroll /really/ fast and node-music-player will glitch out.

I can replicate both.

**Comment by ohnx** [comment]
Oh, seems like adding multiple songs to the same playlist was patched sometime.

However, if you scroll really fast, you can get something like this:
![screenshot 45](https://cloud.githubusercontent.com/assets/6683648/11037500/0fe5d122-86cc-11e5-9979-78d109a200a3.png)

**Comment by benkaiser** [comment]
Ahaha race conditions!  I'll see if I can reproduce it today by Scrolling real fast, and if so I'll just need to have some kind of blocking code that only lets one update function run at a time.

Reopening this for now.

**Comment by benkaiser** [comment]
fixed in https://github.com/benkaiser/stretto/commit/3dd44fa4abb935aff13e67ecca2d140b5b13296c . turns out it was an off by one error in my dynamic scrolling logic
