### ISSUE TITLE
Delete file

### ISSUE THREAD

**Issue by Shuunen** [benkaiser/stretto#61]
Hi,

First, thanks for this great project, I just downloaded it and it works great on my system :)

It would be nice to allow deleting file, i forked the project but I can't see where I can do that, any advise ? 

It need to access the filesystem and delete it by file path, eg: 

`fs.unlink("C:/music/file.mp3");`

**Comment by benkaiser** [comment]
Hi @Shuunen ,

Thanks for taking interest! Glad to hear it's running fine on your windows machine (I'm a linux user myself).

Okay so the client and server communicate via sockets. On the client you should see in various files (just search in project for `socket.emit` to get an idea of what they look like). Then in the server side there is `socket.on` calls, that then go to a function. That function should probably pass it on to the `library_functions.js` file, which would then call the unlinking of the file and removing it from the database.

Let me know if you need any other pointers on how to design this. Also if you you get your code into an almost-completed state, then submit a PR and I can give you feedback on a line-level and we can work though any other issues.

As always, it's awesome to have other people contributing to this project :+1: thanks!

**Comment by Shuunen** [comment]
I'm trying here :
https://github.com/Shuunen/node-music-player/commit/0b4ea74929b4616d4bd5d59760fa35332d7a842c

but this is not working :'(

**Comment by ohnx** [comment]
I'll take a look at this

**Comment by benkaiser** [comment]
Yeah, make sure to have some kind of confirmation so people don't
accidentally delete songs :P

**Comment by ohnx** [comment]
Here's what I'm thinking so far:

1. Add a socket route for `deleteSong`
2. Will loop through all the playlists and remove the song from all playlists
3. Delete the song from the database itself
4. Unlink the file
5. Send the updated playlists to the client (tell the client to update the playlists)

That sound about right?

**Comment by benkaiser** [comment]
That sounds really good 👍

**Comment by Shuunen** [comment]
Yup 😉

**Comment by benkaiser** [comment]
How's this one going @ohnx ?

**Comment by ohnx** [comment]
Have started it, maybe 25% done?

I am going away later this week so I'm not sure if I can finish it before then.

**Comment by benkaiser** [comment]
No worries @ohnx , just checking it was still on your radar :)

**Comment by ohnx** [comment]
ok so I've been working on it, but I will be VERY busy soon...

@benkaiser you can pick it up instead :)

**Comment by benkaiser** [comment]
Sure, want to create a PR with your intermediate code and I'll continue the
PR for you?

**Comment by ohnx** [comment]
It's hard for me to make PRs, so here is the majority of the code I changed:

## `library_functions.js`
```js
exports.removeSong = function(id) {
   // query db for location
  app.db.songs.findOne({_id: id}, function(err, song) {
    var path = app.get('config').music_dir + song.location;
    // query db for the playlists the song is in - how????

    // remove the song from the database
    app.db.songs.remove({_id: id}, {multi: false}, function(err, numRemoved) {
      // unlink the file
      fs.unlink(path, function(err) {
          // broadcast the change
          broadcast('scan_update', {
            type: 'update',
            count: 1,
            completed: 1,
            details: 'Deleted song: ' + song.title + ' - ' + song.artist,
          });
      });
    });
  });
};
```

## `routes/index.js`
```js
// delete a song
function removeSong(req) {
  lib_func.removeSong(req.data.id);
}
```

**Comment by benkaiser** [comment]
Closing out, applies to old architecture of Stretto
