### ISSUE TITLE
Issues with Electron

### ISSUE THREAD

**Issue by ohnx** [benkaiser/stretto#63]
So I decided to try and play around with Electron and nodejs.
I created [this branch](https://github.com/ohnx/node-music-player/tree/electron) to try and experiment.

I cloned that branch and then followed the typical setup (ie, `npm install` then `grunt`).

However, I get a bunch of errors like the following:
![screen shot 2015-10-08 at 8 40 13 pm](https://cloud.githubusercontent.com/assets/6683648/10383432/d20a676a-6dfc-11e5-88c9-2f1c6c7a5c55.png)

Are these caused by Electron not loading the files properly, or is node-music-player loading files in a way that isn't supported?

I notice that none of the files in `/static/libs` seem to be explicitly loaded. Could this be the issue?

**Comment by benkaiser** [comment]
Yep, we use `head.js` to load the resources. See: https://github.com/ohnx/node-music-player/blob/electron/views/base/main_base.html#L46

**Comment by benkaiser** [comment]
Best of luck testing it out with Electron. Would be pretty awesome to ship an Electron app version of node music player!

**Comment by ohnx** [comment]
Those all are loading `/static/js/player` files.

Is there anywhere where `/libs/js` is being loaded, or am I missing something?

**Comment by ohnx** [comment]
The errors appear to be caused by missing Backbone, Marionette, and jQuery libraries.

**Comment by benkaiser** [comment]
See line 47:
```
      "/static/lib/libs.min.js",
```

Grunt generates that file from all the bower components.

**Comment by ohnx** [comment]
Strange, it doesn't seem to be working. I guess I'll try again.

**Comment by ohnx** [comment]
Well, it works now.

I changed nothing.

._.

Thanks!

**Comment by benkaiser** [comment]
Nope wait. Looking at your errors in the console I can see what's causing it.

See that first error, it's originating from the `libs.min.js` file.
Fixing that error will fix the issue.

Did you happen to re-run grunt? Because I'm trying to work out how it could have fixed itself...

**Comment by ohnx** [comment]
Well, now the page loads and looks like this: 
![screen shot 2015-10-08 at 9 05 31 pm](https://cloud.githubusercontent.com/assets/6683648/10383684/55f47338-6e00-11e5-8c8e-a32123b02dec.png)

There still are errors, but it's different compared to what it was like before.

**Comment by benkaiser** [comment]
Okay so it isn't loading the slider library... Might also still be libs/grunt related.

On another note, how would we let users set their music library in electron? Still through the setting screen, or should we have some kind of folder selection?

**Comment by ohnx** [comment]
Actually, I believe I added an explicit `<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>` to fix the issue.

At the moment, it's the same application, just framed in an Electron window, so it's still the same setting screen.

I'm not sure if Electron implements a folder select screen. If it does, then I can try to use it.

**Comment by ohnx** [comment]
I just re-ran grunt, it said no errors:
`
Running "bower:install" (bower) task
>> Installed bower packages
>> Copied packages to /Users/mason/Desktop/node-music-player/static/lib

Running "copy:fontawesome_fonts" (copy) task
Copied 6 files

Running "copy:fontawesome_css" (copy) task
Copied 1 file

Running "uglify:my_target" (uglify) task
>> 1 file created.

Running "cssmin:target" (cssmin) task
>> Ignoring remote @import of "//fonts.googleapis.com/css?family=Raleway:400" as no callback given.
>> 1 file created. 142.06 kB → 128.52 kB

Done, without errors.
`

The slider issue is still there.

**Comment by benkaiser** [comment]
Okay... so we'll have to fix that hack, but sure works for testing it out.

Yeah all good, I'm just getting a few ideas of how to do things differently for an Electron application.

Does:
`static/lib/seiyria-bootstrap-slider/bootstrap-slider.js`
that file exist for you? because that's the slider lib it should be pulling into the `libs.min.js`

**Comment by ohnx** [comment]
It exists for me.

The problematic code seems to be around line 407 in player.js:
```
  this.setScubElem = function(elem){
    this.scrub = elem;
    this.scrub.slider()
      /* disable seeking as soon as slide / click starts.
      * this was added due to an issue causing the slider to update to the old
      * duration even when a click was triggered because of the delay for the
      * slideStop
      */
      .on('slideStart', function(){ player.isSeeking = true; })
      .on('slide', function(slideEvt){ player.scrub_value = slideEvt.value; player.scrubTimeout(); })
      .on('slideStop', function(slideEvt){ player.scrub_value = slideEvt.value; player.scrubTimeoutComplete(); });
  };
```

`elem` appears to not have any attributes

**Comment by benkaiser** [comment]
but the error says: `this.scrub.slider()` is not a function. That means it's failing to load the slider library (because that `.slider()` function comes from there).

As a result anything using the slider won't work.

**Comment by ohnx** [comment]
Ah, okay. Do you want me to try to explicitly load `static/lib/seiyria-bootstrap-slider/bootstrap-slider.js` as well and see if that helps?

**Comment by benkaiser** [comment]
Yeah maybe.
If that fixes it then something in libs just isn't loading / being generated correctly.

**Comment by ohnx** [comment]
Well, I just tried it.

Still doesn't work.

**Comment by benkaiser** [comment]
I think it could be calling that code before the slider library actually loads. And so it'll still fail because the slider library hasn't been loaded before it is used.

Check the network tab to see what order files are coming in. And maybe try re-execute the code with something along the lines of: `player.scrub.slider()` and see if it works after everything is loaded.

**Comment by ohnx** [comment]
I checked the network tab, the explicitly loaded slider plugin is coming way before any other scripts.

**Comment by ohnx** [comment]
If it helps, this isn't working when I just normally run it and go to `localhost:2000` in my browser.

**Comment by ohnx** [comment]
Weird, Safari works...

**Comment by benkaiser** [comment]
Huh. That is weird.

What is the other browser you were trying? Chrome?

**Comment by ohnx** [comment]
Yep.

**Comment by ohnx** [comment]
Funnily enough, http://music.kaiserapps.com/ works just fine in Chrome, it's just my local version that has issues.

**Comment by benkaiser** [comment]
Maybe nuke all the libs and stuff that bower installs and re-run grunt?

**Comment by ohnx** [comment]
>Maybe nuke all the libs and stuff that bower installs and re-run grunt?
Err, how would I do that?

**Comment by benkaiser** [comment]
Look in the gitignore, and remove any of the files that match those rules.
Think that should do it.

**Comment by ohnx** [comment]
Gosh darn, nope.

I removed everything (`node_modules`, `static/lib`, `bower_components`), and then reinstalled it.

Still the same error.

**Comment by ohnx** [comment]
Since this only happens with the latest versions, I may try to download a zipped version of node music player that I know works (the one that runs on my server).

**Comment by benkaiser** [comment]
Yeah, not a bad idea.

**Comment by ohnx** [comment]
So, I just tried it.

I downloaded the zip of everything from my server (that I know for sure works) and extracted it in a folder.

The error is still there.

**Comment by ohnx** [comment]
This might actually be an issue with bootstrap-slider itself. I will try and investigate.

**Comment by benkaiser** [comment]
@ohnx did you end up getting anywhere with this?

**Comment by ohnx** [comment]
Not at the moment, no.

I think I might have some more time in the next week or so to work on it.

**Comment by benkaiser** [comment]
All good @ohnx, no rush.

**Comment by steveostudios** [comment]
Just stumble across this thread... You might have a look at this thread. Apparently Electron (specifically) doesn't like slider
http://stackoverflow.com/questions/32414344/how-do-i-use-bootstrap-slider-in-electron

**Comment by ohnx** [comment]
@steveostudios Ah, thanks for that link.

This makes a lot more sense.

I'll take a look at this and try to use the workaround suggested.

**Comment by benkaiser** [comment]
Yeah. Also I think if its specifically bootstrap-slider related, you should place an issue on their repo. I did a quick search and they had no issues logged for electron.

**Comment by ohnx** [comment]
I'll add one later.

In the meantime, I'll try the workaround mentioned by @steveostudios.

**Comment by ohnx** [comment]
Oh, I need to modify the minified code.

I think I need to try something else...

**Comment by benkaiser** [comment]
Hey @ohnx , I'm working off your changes now and building an electron build. No promises tho ;)

For future reference to people looking for how to solve the jquery and bootstrap slider issues, turns out because in Electron the `module` global variable is set in the browser, it messes up jquery (and hence slider, because it uses jquery). The solution for me, because I didn't care about node-integration in the browser was to add `'node-integration' = false` in my BrowserWindow options like so:

```javascript
mainWindow = new BrowserWindow({width: 800, height: 600, 'node-integration': false});
```

Alternatively you'll have to require jquery (and the slider... not 100% sure how to do that) into the browser window directly, see: https://github.com/atom/electron/issues/254

**Comment by benkaiser** [comment]
Closing as electron binaries have now been shipped.
