### ISSUE TITLE
[enhancement] keyboard shortcuts for stretto

### ISSUE THREAD

**Issue by ohnx** [benkaiser/stretto#81]
move this to trello:

-----
using
```js
var globalShortcut = require('global-shortcut'); // Module for shortcuts
```

one can register media keys like so:
```js
globalShortcut.register('MediaNextTrack', function() { console.log('this hijacks all the media keys'); });
globalShortcut.register('MediaPreviousTrack', function() { console.log('this hijacks all the media keys'); });
globalShortcut.register('MediaPlayPause', function() { console.log('this hijacks all the media keys'); });
```

in the function calls, one could call player events to skip, go back, or play/pause as necessary.

this would be a great enhancement for stretto

**Comment by benkaiser** [comment]
Hi Mason,

That's a brilliant idea!

I'll try add it tonight, might not do a complete rebuild / re-release, but
I'll add it to master. If I don't however, then I'll add it to Trello.

I'm thinking for now just hardcoding them is fine. But maybe down the track
I wouldn't mind having it user-customisable.
