### ISSUE TITLE
Fresh Ubuntu install, ./Stretto shows no life

### ISSUE THREAD

**Issue by mnzt** [benkaiser/stretto#82]
```
root@mnzt:~/Stretto-linux-x64# ./Stretto
root@mnzt:~/Stretto-linux-x64#
```

`ps aux` shows nothing, I'm rather lost on this, I pulled it straight from the releases, 64-bit.

**Comment by benkaiser** [comment]
So stretto doesn't launch at all?

Also is the Ubuntu install the latest?

I might fire up a VM and see if can reproduce and solve the issue.

**Comment by mnzt** [comment]
No launch, nada. Running Ubuntu 14.04.3 LTS

**Comment by benkaiser** [comment]
![virtualbox_ubuntu_07_01_2016_21_29_49](https://cloud.githubusercontent.com/assets/608054/12191159/f4572512-b585-11e5-846c-201416c96292.png)

Just downloaded and ran the live image of Ubuntu 14.04.3 64bit inside a VirtualBox. Was able to successfully download the 64bit Stretto binary for Linux, unzip the folder and run the application as well as downloading a song from soundcloud.

Are you sure your computer is 64bit? You can check in the system settings under the "Details" menu.

If all looks good. The next best option may be to clone the repo and install from source and run electron as a developer and see if it spits out any errors.

**Comment by mnzt** [comment]
I was under the impression that Stretto was a backend/frontend server accessible via a browser client, therefore I was trying to run the executable on a server. My bad!

However, is there an option to run this as a web server, as in http://music.kaiserapps.com/?

**Comment by benkaiser** [comment]
Ah yes! Apologies!

If you run the application, you will actually notice that if you fire up a web browser you will be able to go to http://localhost:2000 and you'll also see the music player!

The application window that gets drawn is using a framework called Electron, that allows Node.js applications that create a server (like Stretto) to be viewed as an application window and also generates binaries for multiple platforms.

If you would like to run the server component on it's own, simply [clone the source and run the installation steps](https://github.com/benkaiser/stretto#dev-installation-instructions).

Let me know if you run into any issues! I'll mark this as closed for now :+1:
