### ISSUE TITLE
Fetch from youtube  issue (reversed artist/song name) 

### ISSUE THREAD

**Issue by mnzt** [benkaiser/stretto#86]
As the title shows, when pulling in from youtube the artist is listed as the track name, and the track name is listed as the artist. 

Am I I the only one experiencing this issue? If not I'll take a look in and send a PR to fix this week.

**Comment by benkaiser** [comment]
@mnzt there is no standard. Although tbh it seems more likely to be the reverse of how we are piecing it apart currently. It is simply using the video title.

If you can think of a better way, then I'm open to hearing it :+1:

**Comment by mnzt** [comment]
The whole artist/track sitting seems to be working well; it's just, backwards. And it's consistently backwards too. 

The defacto for music titles on YouTube is usually `Artist - Track (Year/Album)`. I'll tear open some code later today and see what's going on.

**Comment by benkaiser** [comment]
I know, I've been meaning to fix it but hasn't been high on my priorities.

If you are wanting to send a PR, here is the lines you will be changing:
https://github.com/benkaiser/stretto/blob/master/library_functions.js#L640

May I also ask you add a `.trim()` to each of them after they are separated to remove any whitespace?
