### ISSUE TITLE
CSSMin Dependency

### ISSUE THREAD

**Issue by bheidkamp3** [benkaiser/stretto#96]
Hey,
I'm trying to setup Stretto on my raspberry pi and was getting an npm install error related to CSSMin. Running npm install grunt-contrib-cssmin fixed it. It might make sense to add this to the dependencies

**Comment by benkaiser** [comment]
Any chance you've got the original log from the install?

Otherwise I might try doing an install from scratch to verify if we need it
or not.

**Comment by bheidkamp3** [comment]
I have the console output from the install. Is there a specific log file I should be looking for?

bheidkamp3@mallocshark:~/stretto $ npm run setup

> stretto@0.0.3 setup /home/bheidkamp3/stretto
> npm install && grunt

ffmetadata@1.3.0 node_modules/ffmetadata
├── stream-filter@1.0.0
├── split@0.2.10
├── through@2.3.8
├── stream-combiner@0.0.2 (duplexer@0.0.4)
└── concat-stream@1.0.1 (bops@0.0.6)
Loading "cssmin.js" tasks...ERROR
>> Error: Cannot find module 'maxmin'
Warning: Task "cssmin" not found. Use --force to continue.

Aborted due to warnings.

npm ERR! stretto@0.0.3 setup: `npm install && grunt`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the stretto@0.0.3 setup script.
npm ERR! This is most likely a problem with the stretto package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && grunt
npm ERR! You can get their info via:
npm ERR!     npm owner ls stretto
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.1.17-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "setup"
npm ERR! cwd /home/bheidkamp3/stretto
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/bheidkamp3/stretto/npm-debug.log
npm ERR! not ok code 0

**Comment by benkaiser** [comment]
No that's all. Thanks I'll take a look later when I'm at my computer.

**Comment by ohnx** [comment]
I had no issue on my raspberry pi, was this fixed recently?

**Comment by benkaiser** [comment]
Nothing changed that I know of.

But I'll mark it as closed for now.
