### ISSUE TITLE
Allow drag and drop to add new music files?

### ISSUE THREAD

**Issue by ohnx** [benkaiser/stretto#98]
Add another menu option that's called "upload from computer" that lets you drag and drop music files?

**Comment by benkaiser** [comment]
It sounds good. I'm just worried users of the desktop client will just drag
and drop their whole library instead of properly changing the directory...

**Comment by ohnx** [comment]
true, this is mainly useful for hosted versions :stuck_out_tongue:

**Comment by ohnx** [comment]
perhaps disabling it if stretto is run through electron would be useful?

**Comment by benkaiser** [comment]
Yeah that's a good idea. I'd also like to add conditional code for Electron
to make it launch a native folder picker to select the music folder on
first launch.

**Comment by ohnx** [comment]
Showing a selector for the music folder will still not remove the need to show the settings page - you still have to select your country.

I took a look at dialogs, however, and I pulled up this code that has to be called from the main thread:
```js
var electron = require('electron');
var dialog = electron.dialog;
var chosenDirectory = dialog.showOpenDialog({properties: ['openDirectory']})[0];
```

**Comment by benkaiser** [comment]
Yes that code looks right.
I'm not saying we should drop that page, just that the text input should be
replaced with a button that launches that dialog to select the folder.

**Comment by ohnx** [comment]
That wouldn't be difficult and you wouldn't have to even go through electron!

```html
<input type="file" webkitdirectory directory />
```

is all that would be needed.

**Comment by benkaiser** [comment]
I have a feeling this just gives us the files in that directory, not the
absolute path (which is what we want).

**Comment by benkaiser** [comment]
Closing out, applies to old architecture of Stretto
